src/AppBundle/Entity/Subject.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SubjectRepository")
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks()
 */
class Subject
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string")
     *
     * @var string
     */
    private $title;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $resolved;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $upVote;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $downVote;

    /**
     * @ORM\OneToMany(targetEntity="Reply", mappedBy="subject", cascade={"ALL"})
     *
     * @var Collection<Reply>
     */
    private $replies;

    public function __construct()
    {
        $this->upVote    = $this->downVote = 0;
        $this->resolved  = false;
        $this->createdAt = new \DateTime;
        $this->updatedAt = new \DateTime;
        $this->replies   = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function resolve()
    {
        $this->resolved = true;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return boolean
     */
    public function isResolved()
    {
        return $this->resolved;
    }

    /**
     * @param boolean $resolved
     */
    public function setResolved($resolved)
    {
        $this->resolved = $resolved;
    }

    public function getVotes()
    {
        return $this->upVote - $this->downVote;
    }

    public function isVoteNegative()
    {
        return $this->downVote > $this->upVote;
    }

    public function voteUp()
    {
        $this->upVote++;
    }

    public function voteDown()
    {
        $this->downVote++;
    }

    /**
     * @return Collection<Reply>
     */
    public function getReplies()
    {
        return $this->replies;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updatedAt = new \DateTime;
    }
}

src/AppBundle/Form/Type/SubjectType.php
<?php

namespace AppBundle\Form\Type;

use AppBundle\Entity\Subject;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @author Yohan Giarelli <yohan@giarel.li>
 */
class SubjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults(
                [
                    'data_class' => Subject::class,
                    'method'     => 'POST',
                ]
            );
    }
}

src/AppBundle/Controller/SubjectController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Reply;
use AppBundle\Entity\Subject;
use AppBundle\Form\Type\ReplyType;
use AppBundle\Form\Type\SubjectType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(path="/subjects")
 */
class SubjectController extends Controller
{
    /**
     * @Route(path="/", methods={"GET"}, name="subject_index")
     * @Template()
     */
    public function indexAction()
    {
        return [
            'subjects' => $this->getDoctrine()->getRepository(Subject::class)->findNotResolved()
        ];
    }

    /**
     * @Route(path="/resolved", methods={"GET"}, name="subject_resolved")
     * @Template()
     */
    public function showResolvedAction()
    {
        return [
            'subjects' => $this->getDoctrine()->getRepository(Subject::class)->findResolved()
        ];
    }

    /**
     * @Route(path="/{id}", methods={"GET", "POST"}, name="subject_show", requirements={"id": "\d+"})
     * @Template()
     */
    public function showAction(Request $request, Subject $subject)
    {
        $reply   = new Reply();
        $reply->setSubject($subject);

        $form = $this->createForm(ReplyType::class, $reply, ['method' => 'POST']);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->persist($reply);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('subject_show', ['id' => $subject->getId()]);
        }

        return [
            'subject' => $subject,
            'form'    => $form->createView(),
            'replies' => $this->getDoctrine()->getRepository(Reply::class)->findOrderedBySubject($subject)
        ];
    }

    /**
     * @Route(path="/create", methods={"GET", "POST"}, name="subject_create")
     * @Template()
     */
    public function createAction(Request $request)
    {
        $form = $this->createForm(SubjectType::class);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->persist($subject = $form->getData());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('subject_show', ['id' => $subject->getId()]);
        }

        return ['form' => $form->createView()];
    }

    /**
     * @Route(path="/{id}/resolve", methods={"GET"}, name="subject_resolve")
     */
    public function resolveAction(Subject $subject)
    {
        $subject->resolve();
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('subject_show', ['id' => $subject->getId()]);
    }

    /**
     * @Route(path="/{id}/remove", methods={"GET"}, name="subject_remove")
     */
    public function removeAction(Subject $subject)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $this->getDoctrine()->getManager()->remove($subject);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('subject_index');
    }

    /**
     * @Route(path="/{id}/vote/down", methods={"GET"}, name="subject_vote_down")
     */
    public function voteDownAction(Subject $subject)
    {
        $subject->voteDown();
        $this->getDoctrine()->getManager()->flush();

        return new JsonResponse($subject->getVotes());
    }

    /**
     * @Route(path="/{id}/vote/up", methods={"GET"}, name="subject_vote_up")
     */
    public function voteUpAction(Subject $subject)
    {
        $subject->voteUp();
        $this->getDoctrine()->getManager()->flush();

        return new JsonResponse($subject->getVotes());
    }
}

src/AppBundle/Resources/views/Subject/_subject.html.twig
<h3 class="card-title"{% if subject.voteNegative %} style="background: grey;"{% endif %}>
    <span id="subject-vote-{{ subject.id }}">{{ subject.votes }}</span>
    <a data-vote-on="#subject-vote-{{ subject.id }}" href="{{ path('subject_vote_down', { id: subject.id }) }}">&downarrow;</a>
    <a data-vote-on="#subject-vote-{{ subject.id }}" href="{{ path('subject_vote_up', { id: subject.id }) }}">&uparrow;</a>
    <a href="{{ path('subject_show', {id: subject.id}) }}">
        {{ subject.title }}
    </a>
</h3>
{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('subject_remove', {'id': subject.id}) }}">Supprimer</a>
{% endif %}
<a href="{{ path('subject_resolve', {id: subject.id}) }}">Marquer comme résolu</a>
<section class="card-text">{{ subject.description }}</section>
<span class="card-text">
    <small class="text-muted">
        {{ subject.updatedAt|localizeddate }}
    </small>
</span>

src/AppBundle/Resources/views/Subject/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'Nouveau Sujet' %}

{% block body %}
    <form method="POST" action="{{ path('subject_create') }}" novalidate>
        {{ form_widget(form) }}

        <button type="submit">Valider</button>
    </form>
{% endblock %}

src/AppBundle/Resources/views/Subject/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Sujets' %}

{% block body %}
    {% for subject in subjects %}
        <article class="card card-block">
            <h3 class="card-title">
                {{ subject.votes }}
                <a href="{{ path('subject_show', {id: subject.id}) }}">{{ subject.title }}</a>
            </h3>
            <section class="card-text">{{ subject.description }}</section>
            <span class="card-text">
                <small class="text-muted">
                    {{ subject.updatedAt|localizeddate }}
                </small>
            </span>
        </article>
    {% endfor %}
{% endblock %}

src/AppBundle/Resources/views/Subject/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Sujet ' ~ subject.title %}

{% block body %}
    <article class="card card-block">

        {{ include('@App/Subject/_subject.html.twig', {subject: subject}) }}

        <h4>Replies</h4>

        {% for reply in replies %}
            <article class="reply"{% if reply.voteNegative %} style="background: grey;"{% endif %}>
                <h5>
                    <span id="reply-vote-{{ reply.id }}">{{ reply.votes }}</span>
                    <a data-vote-on="#reply-vote-{{ reply.id }}" href="{{ path('reply_vote_down', { id: reply.id }) }}">&downarrow;</a>
                    <a data-vote-on="#reply-vote-{{ reply.id }}" href="{{ path('reply_vote_up', { id: reply.id }) }}">&uparrow;</a>
                    {{ reply.author }}
                </h5>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('reply_remove', {id: reply.id}) }}">Supprimer</a>
                {% endif %}
                <section class="card-text">{{ reply.text | nl2br }}</section>
                <span class="card-text">
                    <small class="text-muted">
                        {{ subject.updatedAt|localizeddate }}
                    </small>
                </span>
            </article>
        {% endfor %}

        <form action="{{ path('subject_show', {id: subject.id}) }}" method="POST">
            {{ form_widget(form) }}
            {{ form_rest(form) }}

            <button type="submit">Répondre</button>
        </form>
    </article>
{% endblock %}

src/AppBundle/Resources/views/Subject/showResolved.html.twig
{% extends 'base.html.twig' %}

{% block title 'Sujets résolus' %}

{% block body %}
    {% for subject in subjects %}
        <article class="card card-block">
            {{ include('@App/Subject/_subject.html.twig', {subject: subject}) }}
        </article>
    {% endfor %}
{% endblock %}